name: Scheduled Node Job

on:
  schedule:
    # 每天 UTC 03:00 触发（北京时间 11:00）
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run-node-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run project with env
        run: npm run start
        env:
          QQ_COOKIE: ${{ secrets.QQ_COOKIE }}
          TARGET_UIN: ${{ secrets.TARGET_UIN }}
          QQ_UIN: ${{ secrets.QQ_UIN }}
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
          DINGTALK_KEYWORDS: ${{ secrets.DINGTALK_KEYWORDS }}
